name: Unit tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: self-hosted
    concurrency:
      group: uses-tvpaint
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Installing dependencies...
        run: poetry install --no-interaction --with test

      - name: Pytest
        run: poetry run pytest --maxfail 5 --cov=pytvpaint
