name: Unit tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: self-hosted

    concurrency:
      group: uses-tvpaint
      cancel-in-progress: true

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        python-version: [python39, python310, python311, python]

    env:
      VENV_PATH: ${{ github.workspace }}/env_${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Switching Python version
        run: scoop reset ${{ matrix.python-version }}

      - name: Setup Poetry in venv
        run: |
          python -m venv ${{ env.VENV_PATH }}
          ${{ env.VENV_PATH }}/Scripts/pip.exe install poetry

      - name: Installing dependencies...
        run: ${{ env.VENV_PATH }}/Scripts/poetry.exe install --no-interaction --with test

      - name: Pytest
        run: ${{ env.VENV_PATH }}/Scripts/poetry.exe run pytest --maxfail 5 --cov=pytvpaint
